// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package org.zgc.nio.protocol;

public final class Request {
  private Request() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_nio_test_MethodInvokeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_nio_test_MethodInvokeRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\022\014org.nio.test\032\037google/pr" +
      "otobuf/timestamp.proto\"\177\n\023MethodInvokeRe" +
      "quest\022\021\n\trequestId\030\001 \001(\005\022\r\n\005clazz\030\002 \001(\t\022" +
      "\016\n\006method\030\003 \001(\t\022\014\n\004args\030\004 \003(\t\022(\n\004time\030\005 " +
      "\001(\0132\032.google.protobuf.TimestampB\030\n\024org.z" +
      "gc.nio.protocolP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_org_nio_test_MethodInvokeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_nio_test_MethodInvokeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_nio_test_MethodInvokeRequest_descriptor,
        new java.lang.String[] { "RequestId", "Clazz", "Method", "Args", "Time", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
